### ISSUE TITLE
Tag editor doesn't refresh view in tag input fields

### ISSUE THREAD

**Issue by Ilya87** [MBach/Miam-Player#38]
https://yadi.sk/i/5gVjWBvMfojJt

My bad for 2nd part of video - Kid3-qt shows, that Artist tags have really changed - track01 - Apocalyptica2, track02 - Apocalyptica1.

**Comment by MBach** [comment]
Commit https://github.com/MBach/Miam-Player/commit/486892fdb677ea088b7aa1269adfe32f45d8c717 should fix this one and #37

**Comment by Ilya87** [comment]
Not fixed

**Comment by Ilya87** [comment]
Wow! During the test of Tag Editor I caught segmentation fault.
```Program received signal SIGSEGV, Segmentation fault.
0x000000000059a0b5 in LibraryItemModel::insertNode (this=0xd35860, node=0x0)
    at library/libraryitemmodel.cpp:189
189             if (_hash.contains(node->hash())) { ```

**Comment by MBach** [comment]
This means the program has tried to insert a null Node which is odd... I have tested once again on Arch Linux yesterday with various files and I couldn't make Miam-Player to crash!

**Comment by Ilya87** [comment]
It's better to see something once than to hear about it a thousand times.
https://yadi.sk/i/C_WsBmtBhiTif

**Comment by MBach** [comment]
Well... This is pretty obvious with your video (unfortunately). I'll try to reproduce it on my computer tonight!

**Comment by Ilya87** [comment]
I updated VLC-qt and crash disappeared. But the issue is still here - after tag edit current data appears in the table, not in fields with data input.

**Comment by MBach** [comment]
Hi @Ilya87 
Could you please give a chance to commit https://github.com/MBach/Miam-Player/commit/cace47766f957775298f1be4f4b5e991b9b4641c :)

**Comment by Ilya87** [comment]
Fixed! Is it a time to make an AUR build script for Miam-Player? I think YES!

**Comment by MBach** [comment]
Hello @Ilya87 
Thanks for thinking it's time to make a build script. In fact, AUR build script was made a long time ago, but now it seems to redirect to 404 page (last location was https://aur.archlinux.org/packages/miam-player/ ). It may have been renamed or deleted :(
I still have a small issue to fix for the Windows-toolbar plugin in order to create a release in this Repository.

By the way, if you feel confident, you can also try to embed the following plugins: https://github.com/MBach/cover-fetcher and https://github.com/MBach/mini-mode which are cross platforms. AcoustID is in very early stage.

I don't know how it works for AUR build scripts, but for Windows it's quite easy: you just need to put the DLL in the same directory and it's working. On Linux, you may have to write a subscript or describe in a subsection that building plugins must be processed after the player, obviously. And they have to be in a subdirectory called plugins.

**Comment by Ilya87** [comment]
I still don't understand where to put compiled libmini-mode.so and libcover-fetcher.so on Linux. /usr/lib/plugins? or /usr/bin/plugins? In both cases Miam-Player refuses to load them after I create symlink from their build folders to above mentioned folders.

**Comment by Ilya87** [comment]
ping

**Comment by MBach** [comment]
Hi,

Actually I don't know where should be installed these plugins. Right now, final executable is installed in ```/usr/bin``` and dependencies are in ```/usr/lib```. But in the code, I'm looking for subdirectory plugins under the executable, so it should be ```/usr/bin/plugins```.

However, I don't like very much this path. I don't see why my software should create this directory on Linux. I may use this function for each plugin:

    [static] void QCoreApplication::addLibraryPath(const QString &path)

with hardcoded path ```/usr/lib/miam-player/```. I may reduce this hardcoded path with:

    [static] QString QLibraryInfo::location(LibraryLocation loc)

that probably returns ```/usr/lib```.

**Comment by Ilya87** [comment]
I think there are something strange things with install directory (I run qmake in cover fetcher plugin source directory):
Makefile

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/home/mbach/Miam-Player-release/Player/plugins || mkdir -p $(INSTALL_ROOT)/home/mbach/Miam-Player-release/Player/plugins
	-$(INSTALL_PROGRAM) $(TARGET) $(INSTALL_ROOT)/home/mbach/Miam-Player-release/Player/plugins/$(TARGET)
	-$(STRIP) --strip-unneeded $(INSTALL_ROOT)/home/mbach/Miam-Player-release/Player/plugins/$(TARGET)

As you can see it is hardcoded to your path of Miam-Player

**Comment by MBach** [comment]
In fact I'm using these hardcoded paths for building the software with Qt Creator. The build phase is somehow different in Qt Creator and with classic Make command.

My goal is to minimize the rework on such paths. I'm still looking a solution for:

- the developer, so ... me
- people who want to build the software and it's plugin from the sources, like you
- poeple who just want to use final binaries, like packages provided by deb, rpm or so (Ubuntu, etc).
- for people on Windows or on OSX, I provide an installer so everything is embedded in one place

**Comment by Ilya87** [comment]
Yes, plugin needs to be placed in /usr/bin/plugins (I copied .so library there). But with mini-mode I got a segfault. Wait for early report please.
